# NumPy

numpy is python's package for doing math that is more advanced than +-*/

This includes special functions like cosine, exponential, sqrt, ...

On top of this we can use numpy to generate samples from many types of random variables

numpy also has a powerful data type to define vectors, matrices, and tensors

With these data types numpy also allows us to do linear algebra - matrix multiplication and matrix-vector solutions

In [4]:
# the first step of using numpy is to tell python to use it
import numpy as np

In [3]:
print(np.cos(np.pi))
print(np.sqrt(1.21))
print(np.log(np.exp(5.2)))

-1.0
1.1
5.2


In [28]:
# we can create numpy arrays by converting lists
# this is a vector
vec = np.array([1,2,3])
print(vec)
# we can create matrices by converting lists of lists
mat = np.array([[1,2,1],[4,5,9],[1,8,9]])
print('')
print(mat)
print('')
print(mat.T)

[1 2 3]

[[1 2 1]
 [4 5 9]
 [1 8 9]]

[[1 4 1]
 [2 5 8]
 [1 9 9]]


In [29]:
# there are lots of other ways to create numpy arrays
vec2 = np.arange(0,15)
print(vec2)
print('')
vec3 = np.arange(3,21,6)
print(vec3)


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]

[ 3  9 15]


In [19]:
vec4 = np.linspace(0,5,10)
print(vec4)
print('')
print(vec4.reshape(5,2))
vec4_reshaped = vec4.reshape(5,2)
print(vec4_reshaped)
print(vec4)

[0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]

[[0.         0.55555556]
 [1.11111111 1.66666667]
 [2.22222222 2.77777778]
 [3.33333333 3.88888889]
 [4.44444444 5.        ]]
[[0.         0.55555556]
 [1.11111111 1.66666667]
 [2.22222222 2.77777778]
 [3.33333333 3.88888889]
 [4.44444444 5.        ]]
[0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]


In [22]:
mat2 = np.zeros([5,3])
print(mat2)
mat3 = np.ones((3,5))
print('')
print(mat3)
mat4 = np.eye(5)
print('')
print(mat4)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [26]:
# we can +-*/ arrays together if they're the right size
vec5 = np.arange(1,6)
vec6 = np.arange(3,8)
print(vec5)
print(vec6)
print(vec5+vec6)
print(vec5*vec6)
print(1/vec5)
print(np.sqrt(vec6))



[1 2 3 4 5]
[3 4 5 6 7]
[ 4  6  8 10 12]
[ 3  8 15 24 35]

[1.         0.5        0.33333333 0.25       0.2       ]

[1.73205081 2.         2.23606798 2.44948974 2.64575131]


In [28]:
# we can do matrix multiplication
print(mat)
print('')
print(vec)
print()
product = np.matmul(mat,vec)
print(product)


[[1 2 1]
 [4 5 9]
 [1 8 9]]

[1 2 3]

[ 8 41 44]


In [29]:
print(np.linalg.solve(mat,product))
print('')
print(np.linalg.inv(mat))

[1. 2. 3.]

[[ 0.5         0.18518519 -0.24074074]
 [ 0.5        -0.14814815  0.09259259]
 [-0.5         0.11111111  0.05555556]]


In [48]:
# we can find the unique values in an array
vec7 = np.array(['blue','red','orange','purple','purple','orange','Red',6,1.34])
print(vec7)
print(np.unique(vec7))

['blue' 'red' 'orange' 'purple' 'purple' 'orange' 'Red' '6' '1.34']
['1.34' '6' 'Red' 'blue' 'orange' 'purple' 'red']


In [5]:
# we can also use numpy to generate samples of a random variable
rand_mat = np.random.rand(5,5) # uniform random variable
print(rand_mat)
rand_mat2 = np.random.randn(10,5) # standard normal random variable
print('')
print(rand_mat2)


[[0.45447891 0.80095648 0.67273254 0.51557874 0.14882034]
 [0.26375542 0.52611887 0.72434532 0.56587883 0.73360436]
 [0.48710649 0.83632942 0.72219916 0.32857343 0.50214651]
 [0.72702503 0.77696711 0.57026738 0.49542133 0.78057399]
 [0.28267576 0.62153951 0.86757257 0.27160048 0.30516077]]

[[ 7.50312325e-01 -2.57618954e-01 -1.77136722e+00  2.38177232e+00
   1.33921792e+00]
 [-1.85750444e-01 -1.06621397e+00 -8.21490175e-01  6.92454672e-02
  -2.59581545e-01]
 [ 4.39193769e-01  1.87227988e+00 -8.30824016e-01 -3.55738748e-01
   9.24951050e-01]
 [-7.14840503e-01  6.12100804e-01  1.29696234e-01 -2.86709862e-01
   1.60444478e+00]
 [ 1.16499353e+00  1.01672667e+00  2.24305772e-02  7.16678536e-01
  -3.64997088e-01]
 [ 2.75466413e+00 -1.10028838e-03 -1.70316471e-01 -2.63542824e-01
  -1.33846180e+00]
 [ 9.46830974e-01 -1.42871351e-01 -8.55099042e-01 -1.58362476e+00
   1.45541674e-01]
 [ 1.36360281e+00 -1.93104270e-01 -7.84514186e-01 -1.89052643e+00
   2.86309175e-01]
 [-2.56728778e+00 -2.4351846

In [6]:
# we can also use numpy for statistical tools on arrays
print(np.mean(rand_mat))
print(np.std(rand_mat2))

0.5592571496695657
1.128197370548532


In [7]:
print(np.min(rand_mat))
print(np.max(rand_mat2))

0.1488203350988292
2.7546641327393497


In [56]:
# break here for next video!


In [8]:
# how do we access entries in a numpy vector
rand_vec = np.random.randn(19)
print(rand_vec)
print(rand_vec[6])

[ 0.27966593 -0.25061775 -0.57677644 -1.49068652 -0.71572101 -0.61578726
 -0.67296675  1.67344873 -1.62398147  1.80920682  0.32157686  0.50943086
 -1.14268779  0.34766273 -0.0104791   1.38128575  0.1891371   1.08474149
  1.0402064 ]
-0.6729667525993186


In [9]:
# we can access multiple entries at once using :
print(rand_vec[4:9])

[-0.71572101 -0.61578726 -0.67296675  1.67344873 -1.62398147]


In [10]:
# we can also access multiple non-consecutive entries using np.arange
print(np.arange(0,15,3))
print(rand_vec[np.arange(0,15,3)])

[ 0  3  6  9 12]
[ 0.27966593 -1.49068652 -0.67296675  1.80920682 -1.14268779]


In [11]:
# what about matrices
print(rand_mat)

print(rand_mat[1][2])

print(rand_mat[1,2])


[[0.45447891 0.80095648 0.67273254 0.51557874 0.14882034]
 [0.26375542 0.52611887 0.72434532 0.56587883 0.73360436]
 [0.48710649 0.83632942 0.72219916 0.32857343 0.50214651]
 [0.72702503 0.77696711 0.57026738 0.49542133 0.78057399]
 [0.28267576 0.62153951 0.86757257 0.27160048 0.30516077]]
0.7243453221907368
0.7243453221907368


In [17]:
print(rand_mat[0:4,1:4])

[[0.80095648 0.67273254 0.51557874]
 [0.52611887 0.72434532 0.56587883]
 [0.83632942 0.72219916 0.32857343]
 [0.77696711 0.57026738 0.49542133]]


In [18]:
# let's change some values in an array!
print(rand_vec)
rand_vec[3:5] = 4
print('')
print(rand_vec)
rand_vec[3:5] = [1,2]
print('')
print(rand_vec)

[ 0.27966593 -0.25061775 -0.57677644 -1.49068652 -0.71572101 -0.61578726
 -0.67296675  1.67344873 -1.62398147  1.80920682  0.32157686  0.50943086
 -1.14268779  0.34766273 -0.0104791   1.38128575  0.1891371   1.08474149
  1.0402064 ]

[ 0.27966593 -0.25061775 -0.57677644  4.          4.         -0.61578726
 -0.67296675  1.67344873 -1.62398147  1.80920682  0.32157686  0.50943086
 -1.14268779  0.34766273 -0.0104791   1.38128575  0.1891371   1.08474149
  1.0402064 ]

[ 0.27966593 -0.25061775 -0.57677644  1.          2.         -0.61578726
 -0.67296675  1.67344873 -1.62398147  1.80920682  0.32157686  0.50943086
 -1.14268779  0.34766273 -0.0104791   1.38128575  0.1891371   1.08474149
  1.0402064 ]


In [19]:
print(rand_mat)
rand_mat[1:3,3:5] = 0
print('')
print(rand_mat)

[[0.45447891 0.80095648 0.67273254 0.51557874 0.14882034]
 [0.26375542 0.52611887 0.72434532 0.56587883 0.73360436]
 [0.48710649 0.83632942 0.72219916 0.32857343 0.50214651]
 [0.72702503 0.77696711 0.57026738 0.49542133 0.78057399]
 [0.28267576 0.62153951 0.86757257 0.27160048 0.30516077]]

[[0.45447891 0.80095648 0.67273254 0.51557874 0.14882034]
 [0.26375542 0.52611887 0.72434532 0.         0.        ]
 [0.48710649 0.83632942 0.72219916 0.         0.        ]
 [0.72702503 0.77696711 0.57026738 0.49542133 0.78057399]
 [0.28267576 0.62153951 0.86757257 0.27160048 0.30516077]]


In [20]:
sub_mat = rand_mat[0:2,0:3]
print(sub_mat)
sub_mat[:] = 3
print(sub_mat)


[[0.45447891 0.80095648 0.67273254]
 [0.26375542 0.52611887 0.72434532]]
[[3. 3. 3.]
 [3. 3. 3.]]


In [21]:
print(rand_mat)

[[3.         3.         3.         0.51557874 0.14882034]
 [3.         3.         3.         0.         0.        ]
 [0.48710649 0.83632942 0.72219916 0.         0.        ]
 [0.72702503 0.77696711 0.57026738 0.49542133 0.78057399]
 [0.28267576 0.62153951 0.86757257 0.27160048 0.30516077]]


In [ ]:
sub_mat2 = rand_mat[0:2,0:3].copy()
sub_mat2[:] = 99
print(sub_mat2)
print(rand_mat)


In [50]:
# break here for next video
#########################################################
#########################################################
#########################################################





In [55]:
# we can also access entries with logicals
rand_vec = np.random.randn(15)
print(rand_vec)
print(rand_vec>0)

print(rand_vec[rand_vec>0])

[-0.35654939  0.80759239 -1.5494885   0.64363788  0.78073608 -0.24871232
  1.81753196 -1.00989303  1.52548756  0.71723006 -0.66212376 -0.28466709
  0.94048963 -0.61379739  1.64125816]
[False  True False  True  True False  True False  True  True False False
  True False  True]
[0.80759239 0.64363788 0.78073608 1.81753196 1.52548756 0.71723006
 0.94048963 1.64125816]


In [56]:
print(rand_mat2)
print(rand_mat2[rand_mat2>0])

[[ 7.50312325e-01 -2.57618954e-01 -1.77136722e+00  2.38177232e+00
   1.33921792e+00]
 [-1.85750444e-01 -1.06621397e+00 -8.21490175e-01  6.92454672e-02
  -2.59581545e-01]
 [ 4.39193769e-01  1.87227988e+00 -8.30824016e-01 -3.55738748e-01
   9.24951050e-01]
 [-7.14840503e-01  6.12100804e-01  1.29696234e-01 -2.86709862e-01
   1.60444478e+00]
 [ 1.16499353e+00  1.01672667e+00  2.24305772e-02  7.16678536e-01
  -3.64997088e-01]
 [ 2.75466413e+00 -1.10028838e-03 -1.70316471e-01 -2.63542824e-01
  -1.33846180e+00]
 [ 9.46830974e-01 -1.42871351e-01 -8.55099042e-01 -1.58362476e+00
   1.45541674e-01]
 [ 1.36360281e+00 -1.93104270e-01 -7.84514186e-01 -1.89052643e+00
   2.86309175e-01]
 [-2.56728778e+00 -2.43518467e+00 -6.87404536e-01 -1.21802089e+00
   6.08185085e-01]
 [ 1.06094295e+00 -9.36651781e-02  3.77763335e-01  1.61055854e+00
  -3.48338306e-02]]
[0.75031232 2.38177232 1.33921792 0.06924547 0.43919377 1.87227988
 0.92495105 0.6121008  0.12969623 1.60444478 1.16499353 1.01672667
 0.02243058 0.7

In [57]:

print(rand_vec)
print('')
rand_vec[rand_vec>0.5] = -5
print(rand_vec)

[-0.35654939  0.80759239 -1.5494885   0.64363788  0.78073608 -0.24871232
  1.81753196 -1.00989303  1.52548756  0.71723006 -0.66212376 -0.28466709
  0.94048963 -0.61379739  1.64125816]

[-0.35654939 -5.         -1.5494885  -5.         -5.         -0.24871232
 -5.         -1.00989303 -5.         -5.         -0.66212376 -0.28466709
 -5.         -0.61379739 -5.        ]


In [58]:
# let's save some arrays on the disk for use later!
np.save('saved_file_name',rand_mat2)


In [59]:
np.savez('zipped_file_name',rand_mat=rand_mat,rand_mat2=rand_mat2)

In [60]:
# now let's load it
loaded_vec = np.load('saved_file_name.npy')
loaded_zip = np.load('zipped_file_name.npz')

print(loaded_vec)
print('')
print(loaded_zip)

[[ 7.50312325e-01 -2.57618954e-01 -1.77136722e+00  2.38177232e+00
   1.33921792e+00]
 [-1.85750444e-01 -1.06621397e+00 -8.21490175e-01  6.92454672e-02
  -2.59581545e-01]
 [ 4.39193769e-01  1.87227988e+00 -8.30824016e-01 -3.55738748e-01
   9.24951050e-01]
 [-7.14840503e-01  6.12100804e-01  1.29696234e-01 -2.86709862e-01
   1.60444478e+00]
 [ 1.16499353e+00  1.01672667e+00  2.24305772e-02  7.16678536e-01
  -3.64997088e-01]
 [ 2.75466413e+00 -1.10028838e-03 -1.70316471e-01 -2.63542824e-01
  -1.33846180e+00]
 [ 9.46830974e-01 -1.42871351e-01 -8.55099042e-01 -1.58362476e+00
   1.45541674e-01]
 [ 1.36360281e+00 -1.93104270e-01 -7.84514186e-01 -1.89052643e+00
   2.86309175e-01]
 [-2.56728778e+00 -2.43518467e+00 -6.87404536e-01 -1.21802089e+00
   6.08185085e-01]
 [ 1.06094295e+00 -9.36651781e-02  3.77763335e-01  1.61055854e+00
  -3.48338306e-02]]



In [61]:
print(loaded_zip['rand_mat'])
print('')
print(loaded_zip['rand_mat2'])

new_array  = loaded_zip['rand_mat']
print(new_array)

[[3.         3.         3.         0.51557874 0.14882034]
 [3.         3.         3.         0.         0.        ]
 [0.48710649 0.83632942 0.72219916 0.         0.        ]
 [0.72702503 0.77696711 0.57026738 0.49542133 0.78057399]
 [0.28267576 0.62153951 0.86757257 0.27160048 0.30516077]]

[[ 7.50312325e-01 -2.57618954e-01 -1.77136722e+00  2.38177232e+00
   1.33921792e+00]
 [-1.85750444e-01 -1.06621397e+00 -8.21490175e-01  6.92454672e-02
  -2.59581545e-01]
 [ 4.39193769e-01  1.87227988e+00 -8.30824016e-01 -3.55738748e-01
   9.24951050e-01]
 [-7.14840503e-01  6.12100804e-01  1.29696234e-01 -2.86709862e-01
   1.60444478e+00]
 [ 1.16499353e+00  1.01672667e+00  2.24305772e-02  7.16678536e-01
  -3.64997088e-01]
 [ 2.75466413e+00 -1.10028838e-03 -1.70316471e-01 -2.63542824e-01
  -1.33846180e+00]
 [ 9.46830974e-01 -1.42871351e-01 -8.55099042e-01 -1.58362476e+00
   1.45541674e-01]
 [ 1.36360281e+00 -1.93104270e-01 -7.84514186e-01 -1.89052643e+00
   2.86309175e-01]
 [-2.56728778e+00 -2.4351846

In [64]:
# we can also save/load as text files...but only single variables
np.savetxt('text_file_name.txt',rand_mat,delimiter=',')
rand_mat_txt = np.loadtxt('text_file_name.txt',delimiter=',')
print(rand_mat)
print('')
print(rand_mat_txt)

[[3.         3.         3.         0.51557874 0.14882034]
 [3.         3.         3.         0.         0.        ]
 [0.48710649 0.83632942 0.72219916 0.         0.        ]
 [0.72702503 0.77696711 0.57026738 0.49542133 0.78057399]
 [0.28267576 0.62153951 0.86757257 0.27160048 0.30516077]]

[[3.         3.         3.         0.51557874 0.14882034]
 [3.         3.         3.         0.         0.        ]
 [0.48710649 0.83632942 0.72219916 0.         0.        ]
 [0.72702503 0.77696711 0.57026738 0.49542133 0.78057399]
 [0.28267576 0.62153951 0.86757257 0.27160048 0.30516077]]


In [65]:
vec = np.array([4,7,8,9,10,6,1])
print(vec[vec>6])

[ 7  8  9 10]


In [66]:
vec1 = np.array([4, 7, 8, 9, 10, 6, 1])
vec1[vec1>6] = 2
print(vec1)

[4 2 2 2 2 6 1]
